Копылов Дмитрий
urfu-2018/markup-task-7 pull request #31
Opened 2018-11-22 06:22 UTC by Dm17r1y

[Посмотреть решение](https://hruview.herokuapp.com/Dm17r1y/markup-task-7/master/index.html)

2018-11-22 06:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-23 13:33 UTC, msmirnov requested changes
В целом, похоже, но у тебя немного не получилось написать стили по БЭМу. Попробуй почитать вот здесь: https://ru.bem.info/methodology/quick-start/

А ещё шрифт на странице не sans-serif. И можно немного причесать отступы.

🍅

2018-11-23 13:33 UTC, msmirnov commented on index.html
> +    <section class="location__name color_gray">Екатеринбург</section>
Так как `location__name` больше нигде не используется, то серый цвет можно прописать прямо в этот класс. Тут лишний `color_gray`

2018-11-23 13:33 UTC, msmirnov commented on index.html
> +<article class="setting direction_left-top">Настройка</article>
То же самое что и про `location__name`

2018-11-23 13:33 UTC, msmirnov commented on index.html
> +    <section class="login-form__login font-weight_bold margin-left_10px">login</section>
Странная конструкция `margin-left_10px`, стили должны быть прописаны в CSS. Названия классов должны быть человекочитаемы. При этом если ты захочешь изменить отступ с 10px на 15px ты не должен менять ещё и названия стилей. Так как `login-form__login` используется всего один раз, отступы можно прописать внутри стилей для этого класса.

2018-11-23 13:33 UTC, msmirnov commented on index.html
> +    <section class="login-form__login font-weight_bold margin-left_10px">login</section>
При этом использование`font-weight_bold`, кажется, уместно.

2018-11-23 13:33 UTC, msmirnov commented on index.html
> +        <section class="login-form__mail-name margin-left_10px">Почта</section>
В общем, надо все классы, которые отвечают на вопрос "как это выглядит в css" убрать. Название класса должно просто сказать о том, что это за элемент.

2018-11-25 07:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-25 16:02 UTC, msmirnov approved these changes

2018-11-25 16:02 UTC, closed without merging