Юхатский Илья
urfu-2018/markup-task-7 pull request #35
Opened 2018-11-22 07:22 UTC by creewick

https://creewick.github.io/markup-task-7
[Посмотреть решение](https://hruview.herokuapp.com/creewick/markup-task-7/master/index.html)

2018-11-22 07:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-26 10:45 UTC, SemyonMakhaev requested changes
🍅 

1. Контент классно адаптивится под узкие экраны 👍
А вот попап съезжает, давай что-нибудь с этим придумаем
![2018-11-26 15-31-41](https://user-images.githubusercontent.com/18099714/49008785-914b0e80-f190-11e8-9c21-b00226040843.png)

2. Нет индикации, какие виджеты выбраны, а какие нет. Будет удачнее добавить чекбоксы, как на макете

2018-11-26 10:45 UTC, SemyonMakhaev commented on img/bell.svg
> +</svg>
`svg`-документы можно оптимизировать. Для этого существует утилита [svgo](https://github.com/svg/svgo#svgo---)

2018-11-26 10:45 UTC, SemyonMakhaev commented on index.html
> +        <label for="sections-block" class="sidebar__block__title page__link">Посещаемое</label>
Согласно методологии именования БЭМ классы выбираются следующим образом: `имя-блока__имя-элемента`. В данном случае это `sidebar-block__title`

2018-11-26 10:45 UTC, SemyonMakhaev commented on index.css
> +    src: url('fonts/YandexSansDisplay-Regular.woff') format('woff');
`local`

2018-12-04 08:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-06 21:56 UTC, SemyonMakhaev approved these changes
🍏 

Очень круто получилось! 👍

2018-12-06 21:56 UTC, closed without merging