Монин Константин
urfu-2018/markup-task-7 pull request #42
Opened 2018-11-22 10:24 UTC by Kuvadorian

[Посмотреть решение](https://hruview.herokuapp.com/Kuvadorian/markup-task-7/master/index.html)

2018-11-22 10:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-23 12:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-23 13:39 UTC, msmirnov commented
Логотип сжимается на узком экране
![image](https://user-images.githubusercontent.com/2646531/48946220-cd8f2c80-ef4e-11e8-839d-0efa024ea5b5.png)

Попап залезает под картинку, а еще в нем нет индикации выбранных чекбоксов - не понятно, что сейчас включено, а что выключено.
![image](https://user-images.githubusercontent.com/2646531/48946269-edbeeb80-ef4e-11e8-9625-dfa4f91e8297.png)

2018-11-23 13:48 UTC, msmirnov requested changes
В целом, очень круто, только надо немного подтюнить внешний вид.

🍅

2018-11-24 14:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-24 14:44 UTC, Kuvadorian commented
🍏

2018-11-25 16:03 UTC, msmirnov approved these changes

2018-11-25 16:03 UTC, closed without merging