Никишина Маргарита
urfu-2018/markup-task-7 pull request #49
Opened 2018-11-22 11:57 UTC by MargaritaNik

2018-11-22 11:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-28 11:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-09 09:16 UTC, spt30 requested changes
🍅 
Привет! Давай сначала общие замечания поправим:
1) Семантика отсутствует совершенно
2) Перечитай про БЭМ: зачем нужны модификаторы и как их использовать + у элементов не может быть элементов
3) Поправь отступы, чтобы можно было читать  
4) Выпили ненужные файлы

2018-12-09 09:16 UTC, spt30 commented on fonts/demo.html
> +<!DOCTYPE html>
Давай выпиливать лишние файлы)

2018-12-16 09:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2019-01-05 15:30 UTC, closed without merging