Маклакова Елена
urfu-2018/markup-task-7 pull request #55
Opened 2018-11-22 12:28 UTC by elena-i-m98

[Посмотреть решение](https://hruview.herokuapp.com/elena-i-m98/markup-task-7/master/index.html)

2018-11-22 12:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-22 12:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-22 12:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-23 09:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-23 09:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-24 05:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-24 05:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-27 20:59 UTC, chrighter requested changes
🍅

2018-11-27 20:59 UTC, chrighter commented on index.html
>  <body>
![image](https://user-images.githubusercontent.com/22082557/49109722-42df6200-f2ad-11e8-9c50-7b69b6185f8e.png)
Очень много свободного места

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                    <a href="https://clck.ru/EmSMV">Автомобильные новости</a></h2>
![image](https://user-images.githubusercontent.com/22082557/49109770-66a2a800-f2ad-11e8-8106-30835dfa1670.png)
У тебя затемнение, а нужно затенение

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                <input class="search__block__input" type="text">
![image](https://user-images.githubusercontent.com/22082557/49109813-8508a380-f2ad-11e8-84bb-0365587d7744.png)
Давай уберем выделение при фокусе

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                <img class="search__block__tri-angle" src="tri_angle.JPG" alt="треугольник">
Предполагалось, что треугольничек будет сделан не картинкой
Нужно использовать `::after`

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                <div class="search__block__find"><span class="search__block__find__b">Найти</span></div>
![image](https://user-images.githubusercontent.com/22082557/49109967-f6e0ed00-f2ad-11e8-97d6-24c24f2da023.png)
Сейчас кнопка Найти совсем не похожа

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                <input class="search__block__input" type="text">
![image](https://user-images.githubusercontent.com/22082557/49110004-124bf800-f2ae-11e8-84dc-64bdbb14266d.png)
Не соответствует макету
![image](https://user-images.githubusercontent.com/22082557/49110027-22fc6e00-f2ae-11e8-940b-8292def59b1c.png)

2018-11-27 20:59 UTC, chrighter commented on index.html
> +            <a href="" class="search__link">Ещё</a>
ещё

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                    <span class="currency__change">-0,43</span>
Здесь не минус, а длинное тире

2018-11-27 20:59 UTC, chrighter commented on index.html
> +        <a class="header__city" href="https://clck.ru/D5KKN">
![image](https://user-images.githubusercontent.com/22082557/49110116-6951cd00-f2ae-11e8-8b9e-f0e22c0e332e.png)
Давай выровняем

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                        <img class="traffic-jam__picture" src="probki.JPG" alt="светофор"></a>
![image](https://user-images.githubusercontent.com/22082557/49110205-a74ef100-f2ae-11e8-928a-96710dbcf260.png)
Давай сделаем не с помощью картинок, а, например, с помощью `svg`-иконок и текста

2018-11-27 20:59 UTC, chrighter commented on index.html
> +        <article class="content">
![image](https://user-images.githubusercontent.com/22082557/49110285-e11ff780-f2ae-11e8-8cbd-86039e665624.png)
Давай выровняем

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                    <a href="https://yandex.ru/all">Посещаемое</a></h2>
![image](https://user-images.githubusercontent.com/22082557/49110343-0ca2e200-f2af-11e8-9d48-906e483cb4ad.png)
Отсутствует эффект при наведении

2018-11-27 20:59 UTC, chrighter commented on index.css
> +    color: #1e5ebe;
Давай возьмем цвета с главной Яндекса
Например, тут должен быть `#0054b9`

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                <span class="search__example__search-text">калорийность бородинского хлеба</span></p>
Нет эффекта при наведении

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                <div class="treugolnik"></div>
1) Не используется
2) Плохое название класса

2018-11-27 20:59 UTC, chrighter commented on index.html
> +        <a class="header__city" href="https://clck.ru/D5KKN">
![image](https://user-images.githubusercontent.com/22082557/49110554-a2d70800-f2af-11e8-967f-9306b9264b46.png)
Шрифты у блоков, выделенных разными цветами, различаются
Давай приведем к одному виду

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                         о риске закрытия независимых АЗС</a>
`</a>` с новой строки

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                    <img class="news-block__news__line__img" src="ria.JPG" alt="эмблема ria">
Не стоит создавать элементы элементов
Подробнее: https://ru.bem.info/methodology/faq/#Почему-не-стоит-создавать-элементы-элементов-block__elem1__elem2

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                    Без истории посещений</span>
`<span>` с новой строки

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                <br>
Давай отступ сделаем при помощи `margin/padding`, без `<br>`

2018-11-27 20:59 UTC, chrighter commented on index.html
> +            <div class="news-block_advertising-square">
Давай добавим семантику

2018-11-27 20:59 UTC, chrighter commented on index.html
> +            <div class="news-block_advertising-square">
`advertising-square` - это точно модификатор?
https://ru.bem.info/methodology/key-concepts/#Модификатор

2018-11-27 20:59 UTC, chrighter commented on index.html
> +            <a href="" class="search__link">Видео</a>
Давай сделаем ссылку `#`

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                    <a href="https://yandex.ru/all">Посещаемое</a></h2>
`<h2>` с новой строки
Проверь, пожалуйста, везде закрывающие теги

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                    <a href="https://clck.ru/Emus9">
При наведении контент "прыгает"

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                <p class="weather__text">Днём -10, вечером -10</p>
Здесь длинное тире, а не минус

2018-11-27 20:59 UTC, chrighter commented on index.html
> +                <p class="weather__text">Днём -10, вечером -10</p>
Кажется, картинка не соответствует тексту

2018-11-29 03:26 UTC, elena-i-m98 commented on index.html
>  <body>
ой, неожиданно...

2018-11-29 11:44 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-29 12:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-29 12:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-29 12:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-03 12:22 UTC, chrighter requested changes
🍅

2018-12-03 12:22 UTC, chrighter commented on index.css
> +/* .cars-news__block::-webkit-scrollbar
Лишние комментарии

2018-12-03 12:22 UTC, chrighter commented on index.html
>                      <a href="https://clck.ru/EmSMV">Автомобильные новости</a></h2>
А сейчас вообще ни затемнения, ни затенения ((

2018-12-03 12:22 UTC, chrighter commented on k.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Давай для оптимизации `svg` будем использовать `svgo`
https://www.npmjs.com/package/svgo

2018-12-03 12:43 UTC, chrighter requested changes
🍅

2018-12-03 12:43 UTC, chrighter commented on index.html
>  <body>
![image](https://user-images.githubusercontent.com/22082557/49373490-2796ab80-f720-11e8-91a5-e90ef891aa51.png)
Все равно много места

2018-12-03 12:43 UTC, chrighter commented on index.html
> +        <img class="emblem" src="yandex.JPG" alt="эмблема Яндекса">
![image](https://user-images.githubusercontent.com/22082557/49373553-57de4a00-f720-11e8-8f00-84fffa3d775e.png)
Слишком большой отступ

2018-12-03 12:43 UTC, chrighter commented on index.html
> +                    <a href="https://yandex.ru/all">Посещаемое</a></h2>
![image](https://user-images.githubusercontent.com/22082557/49373648-a12e9980-f720-11e8-9da9-a32a6cc4c3b6.png)
Давай выровняем, как третий столбик
Хотя в третьем столбике, я еще бы выровняла Погоду

2018-12-03 12:43 UTC, chrighter commented on index.html
> +                    <a href="https://yandex.ru/all">Посещаемое</a></h2>
Уже практически совсем хорошо, вот только тире не выделяется при наведении
![image](https://user-images.githubusercontent.com/22082557/49373711-cc18ed80-f720-11e8-9055-cf9742570166.png)

![image](https://user-images.githubusercontent.com/22082557/49373728-da670980-f720-11e8-8d0e-0456b5ee4b3e.png)

2018-12-03 12:43 UTC, chrighter commented on index.html
> +                    <a href="https://yandex.ru/all">Телепрограмма</a>
Проверь, совпадают ли выделения при наведении здесь и в других местах

2018-12-04 19:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-05 03:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-05 06:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-12-05 07:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-05 20:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-06 15:20 UTC, chrighter requested changes
🍅

2018-12-06 15:20 UTC, chrighter commented on index.html
> +                    <img class="news-block__news__line__img" src="ria.JPG" alt="эмблема ria">
Все равно создаешь элементы элементов

2018-12-06 15:20 UTC, chrighter commented on index.html
>  <body>
![image](https://user-images.githubusercontent.com/22082557/49591482-629f1600-f990-11e8-821e-c1f7f1e60b3e.png)
Еще немного осталось

2018-12-06 15:20 UTC, chrighter commented on index.html
> +                            <span class="not-hover">—</span>свежие предложения</p>
1) Давай не будем называть классы `css`-свойствами элементов
2) Это название не соответствует БЭМ (В БЭМ классы чаще всего называются существительными, прилагательные и причастия используются для модификаторов)

2018-12-06 15:20 UTC, chrighter commented on index.html
> +                        <img class="traffic-jam__picture" src="probki.JPG" alt="светофор"></a>
Все еще картинки

2018-12-06 15:20 UTC, chrighter commented on w.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="67" height="48"><image width="67" height="48" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEMAA
Это есть на странице?

2018-12-06 15:20 UTC, chrighter commented on p.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="81" height="39"><image width="81" height="39" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFEAA
А это есть на странице?
А еще непонятное название

2018-12-06 15:20 UTC, chrighter commented on index.html
> +                    <a href="https://yandex.ru/all">Телепрограмма</a>
В других местах, кажется, не проверила
Посмотри, правильно ли выделяется в Найдется все, рядом со строкой поиска, в Посещаемом и тд

2018-12-13 14:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-28 08:44 UTC, chrighter approved these changes

2018-12-28 08:44 UTC, closed without merging